import math
from typing import Any, Dict, List, Optional, Tuple



Point = Tuple[float, float]


def _poly_area(points: List[Point]) -> float:
    if len(points) < 3:
        return 0.0
    area = 0.0
    for i in range(len(points)):
        x1, y1 = points[i]
        x2, y2 = points[(i + 1) % len(points)]
        area += x1 * y2 - x2 * y1
    return abs(area) / 2.0


def _bbox(points: List[Point]) -> Tuple[float, float, float, float]:
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    return min(xs), min(ys), max(xs), max(ys)


def _centroid(points: List[Point]) -> Point:
    if not points:
        return (0.0, 0.0)
    x = sum([p[0] for p in points]) / float(len(points))
    y = sum([p[1] for p in points]) / float(len(points))
    return (x, y)


def _distance(a: Point, b: Point) -> float:
    return math.hypot(a[0] - b[0], a[1] - b[1])


def parse_dxf(file_path: str) -> Dict[str, Any]:
    try:
        import ezdxf  # type: ignore
    except Exception as e:
        raise RuntimeError(f"ezdxf is required to parse DXF files: {e}")

    doc = ezdxf.readfile(file_path)
    msp = doc.modelspace()

    plot_poly = _first_closed_polyline(msp, layer="PLOT_BOUNDARY")
    building_poly = _first_closed_polyline(msp, layer="BUILDING")

    if not plot_poly or not building_poly:
        raise ValueError("DXF is missing PLOT_BOUNDARY or BUILDING closed polylines")

    plot_points = plot_poly
    building_points = building_poly

    plot_area = _poly_area(plot_points)
    building_area = _poly_area(building_points)

    plot_minx, plot_miny, plot_maxx, plot_maxy = _bbox(plot_points)
    b_minx, b_miny, b_maxx, b_maxy = _bbox(building_points)

    setbacks = {
        "front": b_miny - plot_miny,
        "rear": plot_maxy - b_maxy,
        "side_left": b_minx - plot_minx,
        "side_right": plot_maxx - b_maxx,
    }

    # Room polygons are closed polylines on WALLS layer.
    room_polys = _all_closed_polylines(msp, layer="WALLS")
    labels = _all_mtext(msp, layer="ANNOTATIONS")

    rooms: List[Dict[str, Any]] = []
    for poly in room_polys:
        poly_points = poly
        area = _poly_area(poly_points)
        center = _centroid(poly_points)

        label = _nearest_label(labels, center)
        name = label.get("name") if label else "(Unnamed)"

        category = _categorize_room(name)
        rooms.append(
            {
                "name": name,
                "category": category,
                "area": area,
                "polygon": [[p[0], p[1]] for p in poly_points],
                "center": [center[0], center[1]],
            }
        )

    # Building height from annotation text (generated by generator).
    building_height = _extract_number_from_labels(labels, prefix="Building Height")

    doors = _parse_doors(msp)

    derived = _derive_fields(plot_area, building_area, setbacks, rooms, doors, building_height)

    return {
        "source": "DXF",
        "file_path": file_path,
        "plot": {
            "area": plot_area,
            "boundary": [[p[0], p[1]] for p in plot_points],
            "bbox": [plot_minx, plot_miny, plot_maxx, plot_maxy],
        },
        "building": {
            "footprint_area": building_area,
            "outline": [[p[0], p[1]] for p in building_points],
            "bbox": [b_minx, b_miny, b_maxx, b_maxy],
            "setbacks": setbacks,
            "height": building_height,
        },
        "rooms": rooms,
        "doors": doors,
        "derived": derived,
    }


def _first_closed_polyline(msp, layer: str) -> Optional[List[Point]]:
    for e in msp.query(f"LWPOLYLINE[layer=='{layer}']"):
        try:
            if not e.closed:
                continue
            return [(float(p[0]), float(p[1])) for p in e.get_points("xy")]
        except Exception:
            continue
    return None


def _all_closed_polylines(msp, layer: str) -> List[List[Point]]:
    polys: List[List[Point]] = []
    for e in msp.query(f"LWPOLYLINE[layer=='{layer}']"):
        try:
            if not e.closed:
                continue
            pts = [(float(p[0]), float(p[1])) for p in e.get_points("xy")]
            if len(pts) >= 3:
                polys.append(pts)
        except Exception:
            continue
    return polys


def _all_mtext(msp, layer: str) -> List[Dict[str, Any]]:
    labels: List[Dict[str, Any]] = []
    for e in msp.query(f"MTEXT[layer=='{layer}']"):
        try:
            text = (e.text or "").replace("\\P", "\n")
            ins = e.dxf.insert
            labels.append(
                {
                    "text": text,
                    "insert": (float(ins[0]), float(ins[1])),
                    "name": _parse_room_name(text),
                }
            )
        except Exception:
            continue
    return labels


def _parse_room_name(text: str) -> str:
    t = (text or "").strip()
    if not t:
        return ""
    first_line = t.splitlines()[0]
    return first_line.strip()


def _nearest_label(labels: List[Dict[str, Any]], center: Point) -> Optional[Dict[str, Any]]:
    if not labels:
        return None
    best = None
    best_d = None
    for l in labels:
        d = _distance(center, l["insert"])
        if best_d is None or d < best_d:
            best = l
            best_d = d
    return best


def _extract_number_from_labels(labels: List[Dict[str, Any]], prefix: str) -> Optional[float]:
    for l in labels:
        text = (l.get("text") or "")
        for line in text.splitlines():
            if line.strip().lower().startswith(prefix.lower()):
                # Examples: "Building Height: 9.0m"
                parts = line.split(":", 1)
                if len(parts) < 2:
                    continue
                s = parts[1]
                s = s.replace("m", " ").replace("M", " ")
                try:
                    return float(s.strip().split()[0])
                except Exception:
                    continue
    return None


def _categorize_room(name: str) -> str:
    n = (name or "").lower()
    if "bedroom" in n:
        return "Bedroom"
    if "living" in n:
        return "Living"
    if "kitchen" in n:
        return "Kitchen"
    if "bath" in n:
        return "Bathroom"
    if "corridor" in n or "hall" in n:
        return "Corridor"
    if "majlis" in n:
        return "Majlis"
    return "Other"


def _parse_doors(msp) -> List[Dict[str, Any]]:
    doors: List[Dict[str, Any]] = []
    for e in msp.query("INSERT[layer=='DOORS']"):
        try:
            attrs = {}
            for a in e.attribs:
                attrs[str(a.dxf.tag).upper()] = str(a.dxf.text)
            width = None
            if "WIDTH" in attrs:
                try:
                    width = float(attrs["WIDTH"])
                except Exception:
                    width = None
            door_type = attrs.get("TYPE") or "INTERIOR"
            doors.append(
                {
                    "name": attrs.get("NAME") or e.dxf.name,
                    "type": door_type.upper(),
                    "width": width,
                    "insert": [float(e.dxf.insert[0]), float(e.dxf.insert[1])],
                }
            )
        except Exception:
            continue
    return doors


def _derive_fields(
    plot_area: float,
    building_area: float,
    setbacks: Dict[str, float],
    rooms: List[Dict[str, Any]],
    doors: List[Dict[str, Any]],
    building_height: Optional[float],
) -> Dict[str, Any]:
    bedrooms = [r for r in rooms if r.get("category") == "Bedroom"]
    bathrooms = [r for r in rooms if r.get("category") == "Bathroom"]

    living = next((r for r in rooms if r.get("category") == "Living"), None)
    kitchen = next((r for r in rooms if r.get("category") == "Kitchen"), None)
    corridor = next((r for r in rooms if r.get("category") == "Corridor"), None)

    interior_doors = [d for d in doors if (d.get("type") or "").upper() != "EXTERIOR"]
    exterior_doors = [d for d in doors if (d.get("type") or "").upper() == "EXTERIOR"]

    corridor_width = None
    if corridor and corridor.get("polygon"):
        pts = [(float(p[0]), float(p[1])) for p in corridor["polygon"]]
        minx, miny, maxx, maxy = _bbox(pts)
        corridor_width = min(maxx - minx, maxy - miny)

    derived: Dict[str, Any] = {
        "front_setback": float(setbacks.get("front")),
        "rear_setback": float(setbacks.get("rear")),
        "side_setback_min": float(min(setbacks.get("side_left"), setbacks.get("side_right"))),
        "lot_coverage_pct": (building_area / plot_area) * 100.0 if plot_area else None,
        "building_height": float(building_height) if building_height is not None else None,
        "living_area": float(living.get("area")) if living else None,
        "kitchen_area": float(kitchen.get("area")) if kitchen else None,
        "corridor_width": corridor_width,
        "bedroom_areas": [{"name": r.get("name"), "value": float(r.get("area"))} for r in bedrooms],
        "bathroom_areas": [{"name": r.get("name"), "value": float(r.get("area"))} for r in bathrooms],
        "interior_door_widths": [{"name": d.get("name"), "value": float(d.get("width"))} for d in interior_doors if d.get("width") is not None],
        "exterior_door_width": float(exterior_doors[0].get("width")) if exterior_doors and exterior_doors[0].get("width") is not None else None,
    }

    return derived
