/**
 * Platform shell — DO NOT EDIT THIS FILE.
 *
 * This file wires up SSO authentication, current-user loading, the optional
 * watermark, the user menu, and logout. These platform capabilities are
 * maintained by the application platform. Do not modify or delete any code in
 * this file unless the user explicitly asks to change these capabilities.
 *
 * Write all business UI and logic in src/business.tsx (and the files it
 * imports); do not add business code here. The signed-in user is passed to
 * <Business /> through the `user` prop.
 */
import { useEffect, useState } from 'react'

import {
  AccessDeniedError,
  fetchCurrentUser,
  getAuthService,
  redirectToSSO,
  resolveJwt,
  type UserResponse,
} from './lib/auth'
import './App.css'
import Business from './business'

function App() {
  const [user, setUser] = useState<UserResponse | null>(null)
  const [accessDeniedOwner, setAccessDeniedOwner] = useState<string | null>(null)
  const [, setAuthToken] = useState<string | null>(null)
  const [authReady, setAuthReady] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)


  useEffect(() => {
    let cancelled = false

    // For external demos / technical reviews, allow bypassing internal SSO.
    if (import.meta.env.VITE_DISABLE_SSO === 'true') {
      setUser({
        username: 'demo',
        name: 'Demo User',
        avatar_url: '',
        terminated: false,
      })
      setAccessDeniedOwner(null)
      setAuthToken(null)
      setAuthReady(true)
      return () => {
        cancelled = true
      }
    }

    const initAuth = async () => {
      const urlParams = new URLSearchParams(window.location.search)
      const isSsoCallback = urlParams.get('auth_callback') === 'true'

      try {
        const service = await getAuthService()
        const jwt = await service.getJwt()

        if (!jwt) {
          if (isSsoCallback) {
            console.error('Unable to get a JWT after returning from SSO.')
            if (!cancelled) {
              setAccessDeniedOwner('页面所有者')
              setUser(null)
              setAuthToken(null)
              setAuthReady(true)
            }
          } else {
            await redirectToSSO()
          }
          return
        }

        if (!cancelled) {
          setAuthToken(jwt)
        }

        if (isSsoCallback) {
          urlParams.delete('auth_callback')
          const search = urlParams.toString()
          window.history.replaceState(
            {},
            document.title,
            `${window.location.pathname}${search ? `?${search}` : ''}${window.location.hash}`,
          )
        }

        try {
          const currentUser = await fetchCurrentUser(jwt)
          const currentJwt = await resolveJwt()
          if (!cancelled) {
            setAccessDeniedOwner(null)
            setUser(currentUser)
            setAuthToken(currentJwt)
            setAuthReady(true)
          }
        } catch (error) {
          if (error instanceof AccessDeniedError) {
            if (!cancelled) {
              setAccessDeniedOwner(error.owner)
              setUser(null)
              setAuthReady(true)
            }
            return
          }

          if (!cancelled) {
            setAccessDeniedOwner('页面所有者')
            setUser(null)
            setAuthToken(null)
            setAuthReady(true)
          }
          console.error('Unable to load the signed-in user:', error)
        }
      } catch (error) {
        console.error('Unable to initialize SSO authentication:', error)
        if (!isSsoCallback) {
          try {
            await redirectToSSO()
          } catch (redirectError) {
            console.error('Unable to redirect to SSO:', redirectError)
            if (!cancelled) {
              setAccessDeniedOwner('页面所有者')
              setUser(null)
              setAuthToken(null)
              setAuthReady(true)
            }
          }
        } else if (!cancelled) {
          setAccessDeniedOwner('页面所有者')
          setUser(null)
          setAuthToken(null)
          setAuthReady(true)
        }
      }
    }

    void initAuth()

    return () => {
      cancelled = true
    }
  }, [])

  const handleLogout = async () => {
    try {
      const service = await getAuthService()
      await service.logout()
      setUser(null)
      setAccessDeniedOwner(null)
      setAuthToken(null)
      setMenuOpen(false)
    } catch (error) {
      console.error('Unable to log out:', error)
    }
  }

  const avatarLabel = user ? `${user.name}的头像` : ''
  const avatarInitial = user ? (user.name || user.username).slice(0, 1) : ''
  const displayName = user ? user.username || user.name : ''
  const hasAccessDeniedOwner = accessDeniedOwner && accessDeniedOwner !== '页面所有者'

  return (
    <div className='app-shell'>
      <header className='app-header'>
        <h1>Plans & Compliance CoPilot — Real Engine Demo</h1>
        {user && (
          <div
            className={`user-menu${menuOpen ? ' is-open' : ''}`}
            onMouseEnter={() => setMenuOpen(true)}
            onMouseLeave={() => setMenuOpen(false)}
          >
            <button
              className='user-menu-button'
              type='button'
              aria-label='打开用户菜单'
              aria-haspopup='menu'
              aria-expanded={menuOpen}
              onClick={() => setMenuOpen((open) => !open)}
            >
              {user.avatar_url ? (
                <img
                  className='user-avatar'
                  src={user.avatar_url}
                  alt={avatarLabel}
                  referrerPolicy='no-referrer'
                />
              ) : (
                <span className='user-avatar user-avatar-fallback' aria-hidden='true'>
                  {avatarInitial}
                </span>
              )}
              <span className='user-menu-name'>{displayName}</span>
            </button>
            <div className='user-menu-popover' role='menu'>
              <div className='user-menu-profile'>
                {user.avatar_url ? (
                  <img
                    className='user-menu-avatar'
                    src={user.avatar_url}
                    alt=''
                    referrerPolicy='no-referrer'
                  />
                ) : (
                  <span className='user-menu-avatar user-avatar-fallback' aria-hidden='true'>
                    {avatarInitial}
                  </span>
                )}
                <div>
                  <strong>{user.name}</strong>
                  <span>{user.username}</span>
                </div>
              </div>
              <div className='user-menu-divider' />
              <button
                className='logout-button'
                type='button'
                role='menuitem'
                onClick={() => void handleLogout()}
              >
                <span aria-hidden='true'>⏻</span>
                退出登录
              </button>
            </div>
          </div>
        )}
      </header>

      <main className='template-content'>
        {/* PROTECTED PLATFORM ACCESS GATE
            Keep this wrapper in App.tsx so generated business code cannot
            render over the no-permission state. Write app UI in Business. */}
        {!authReady ? (
          <div className='auth-loading' role='status' aria-live='polite'>
            正在校验访问权限...
          </div>
        ) : accessDeniedOwner ? (
          <div className='access-denied' role='alert'>
            <span>抱歉您无权限访问该页面，请向</span>
            {hasAccessDeniedOwner ? (
              <span className='access-denied-owner'>{accessDeniedOwner}</span>
            ) : (
              <span>{accessDeniedOwner}</span>
            )}
            <span>申请权限</span>
          </div>
        ) : (
          <Business user={user} />
        )}
      </main>
    </div>
  )
}

export default App
